In [1]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv(r'D:\Data science\Data sample\raw.githubusercontent.com_amankharwal_Website-data_master_IRIS.csv')
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
new_df=pd.get_dummies(df['species'])
dumm=(new_df==1).astype(int)
dumm

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [4]:
merged=pd.concat([dumm,df],axis='columns')
merged

,Iris-setosa,Iris-versicolor,Iris-virginica,sepal_length,sepal_width,petal_length,petal_width,species
0,1,0,0,5.1,3.5,1.4,0.2,Iris-setosa
1,1,0,0,4.9,3.0,1.4,0.2,Iris-setosa
2,1,0,0,4.7,3.2,1.3,0.2,Iris-setosa
3,1,0,0,4.6,3.1,1.5,0.2,Iris-setosa
4,1,0,0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...
145,0,0,1,6.7,3.0,5.2,2.3,Iris-virginica
146,0,0,1,6.3,2.5,5.0,1.9,Iris-virginica
147,0,0,1,6.5,3.0,5.2,2.0,Iris-virginica
148,0,0,1,6.2,3.4,5.4,2.3,Iris-virginica
149,0,0,1,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
X=merged.drop(['species'],axis='columns')
y=merged['species']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)
print('Predicted values :',y_pred)
# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Predicted values : ['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']
Accuracy: 1.0